version: '2'

services:
  php:
    build:
      context: docker/php/
    working_dir: /var/www
    volumes:
      - ./:/var/www
    links:
      - mysql

  nginx:
    build:
      context: docker/nginx/
    working_dir: /var/www
    volumes_from:
      - php
    ports:
      - "8002:80"

  mysql:
    image: mysql:5.7
#    volumes:
#      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: wiredpea
    ports:
      - "33006:3306"

#volumes:
#  dbdata:
